name: Deploy daily

on:
  schedule:
  - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          cd client
          npm install
          npm run build
        env:
          CI: true
      - name: test
        run: npm run test
        env:
          CI: true
     - name: deploy
       uses: ./.github/actions/deploy
