name: Test and deploy
on:
  push:
    branches:
      - master # Push events on master branch
  schedule:
    - cron: "1 */8 * * *"

jobs:
  TestAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: npm install
        run: cd client && npm install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - name: npm build
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: true
        with:
          args: ./gh-build.sh
      - name: test
        run: |
          cd client
          npm run test
      - name: deploy
        run: |
          curl -X POST -d {} ${{ secrets.BUILD_HOOK }}
