name: Tests
on:
  push:
    branches-ignore:
      - master # Push events on master branc

jobs:
  testAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          cd client
          npm install
          npm run build
      - name: test
        run: |
          cd client
          npm run test
