# name: Test
# on:
#   push:
#     branches:
#       - master # Push events on master branch

# jobs:
#   Test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: Use Node.js 18.x
#         uses: actions/setup-node@v1
#         with:
#           node-version: "18.x"
#       - name: npm install
#         run: cd client && npm install
#       - name: get data
#         run: |
#           cd client
#           npm run getData
#       - name: build
#         run: |
#           cd client
#           npm rebuild sharp --force
#           npm run build
#       - name: test
#         run: |
#           cd client
#           npm run test
