name: Test and deploy
on:
  push:
    branches:
      - 2019 # Push events on master branc
  # schedule:
  #   - cron: "1 */8 * * *"

jobs:
  TestAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: npm install and build
        run: |
          cd client
          npm install
          npm run build
      - name: test
        run: |
          cd client
          npm run test
      # - name: deploy
      #   run: |
      #     curl -X POST -d {} ${{ secrets.BUILD_HOOK }}
